CREATE TABLE public.glaciers_variable (
	glacier_id character varying(20) NOT NULL,
	submission_id integer NOT NULL,
	glac_name character varying(28),
	area numeric,
	db_area numeric,
	perimeter numeric,
	min_elev numeric,
	max_elev numeric,
	mean_elev numeric,
	geog_area character varying(20),
	in_county text,
	in_basin text,
	num_basins smallint,
	fcode integer DEFAULT 37800,
	date timestamp NOT NULL,
	geom geometry,
	max_width numeric,
	max_length numeric,
	slope smallint,
	aspect smallint,
	connect smallint,
	surging smallint,
	linkages smallint,
	form smallint,
	term_type smallint,
	x_coord numeric,
	y_coord numeric,
	loc_unc_x smallint,
	loc_unc_y smallint,
	glob_unc_x smallint,
	glob_unc_y smallint,
	prime_class smallint,
	frontal_char smallint,
	long_char smallint,
	tongue_act smallint,
	moraines1 smallint,
	moraines2 smallint,
	source_nourish smallint,
	min_elev_exp smallint,
	mean_elev_acy smallint,
	mean_elev_abl smallint,
	activity_start smallint,
	activity_end smallint,
	snowline_acy smallint,
	snowline_date smallint,
	mean_depth smallint,
	deapth_acy smallint,
	area_acy smallint,
	area_exp smallint,
	mean_width smallint,
	mean_length smallint,
	max_len_ex smallint,
	max_len_ab smallint,
	orient_acc text,
	orient_abl text,
	remarks text,
	CONSTRAINT glims_polygons_pkey PRIMARY KEY (glacier_id),
	CONSTRAINT glaciers_glac_id_un UNIQUE (glacier_id)
);